
project_id = "rzmfwwkumniuwenammaj"

[functions.consent-config]
verify_jwt = false

[http.cors]
allow_origins = ["*"]
exposed_headers = ["Content-Length", "Content-Type", "Authorization"]
max_age = 600

