
project_id = "rzmfwwkumniuwenammaj"

[functions.consent-config]
verify_jwt = false

[functions.admin-setup]
verify_jwt = false

[functions.admin-settings]
verify_jwt = true

[functions.admin-role]
verify_jwt = true

[http.cors]
allow_origins = ["*"]
exposed_headers = ["Content-Length", "Content-Type", "Authorization"]
max_age = 600
