
# This file is used to configure the Supabase project.
project_id = "rzmfwwkumniuwenammaj"

[api]
enabled = true
port = 54321
endpoint = "http://localhost"

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true

[functions]
enabled = true

[functions.consent-config]
verify_jwt = false

[functions.admin-role]
verify_jwt = true

[functions.admin-settings]
verify_jwt = true

[functions.admin-setup]
verify_jwt = true

[functions.admin-plans]
verify_jwt = true

[functions.consent-analytics]
verify_jwt = false
