// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzmfwwkumniuwenammaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6bWZ3d2t1bW5pdXdlbmFtbWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTMyMTcsImV4cCI6MjA2MjcyOTIxN30.Lmyu_VrAhzFC6Kq9oN2am_PMHJd_Hq4tu-TJXy1FkzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);